# Generated by Django 2.0.4 on 2018-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomateuser',
            name='bio',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomateuser',
            name='picture',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
