# Generated by Django 2.0.4 on 2018-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180424_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomateuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='pic_folder'),
        ),
    ]
