# Generated by Django 2.0.4 on 2018-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180424_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomateuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='XOKt08AJeyvQMGHK31eef6c6-ebe2-4c5f-8fc1-4ef57da1717c'),
        ),
    ]
