# Generated by Django 2.0.4 on 2018-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180425_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomateuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='83qVgl3g2CwApFXi18de614c-2ff1-4d17-a404-d53c234ca5fe'),
        ),
    ]
